version: "3.8"

services:
  web:
    image: hannibal1022/php-sample-app
    container_name: php_app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: hannibal1022/mysql-db
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

