# Usar una imagen oficial de MySQL
FROM mysql:5.7

# Configurar variables de entorno
ENV MYSQL_DATABASE=appdb
ENV MYSQL_USER=appuser
ENV MYSQL_PASSWORD=password123
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Exponer el puerto 3306
EXPOSE 3306

